version: 2
jobs:
  build_master:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Create .env
          command: |
            cat > .env << EOF1
            VUE_APP_BASE_URL=https://grader.monkeyatc.com/api
            VUE_APP_DEBUG=false
            EOF1
      - run: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  deploy_master:
    working_directory: ~/project
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Copy to VM
          command: scp -r circleci@grader.monkeyatc.com:/var/www/html ./dist/.

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_master
      - deploy_master:
          requires:
            - build_master
          filters:
            branches:
              only:
                - master
